name: SSL Expiration Check

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:

jobs:
  ssl-expiration-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run the script
      run: bash ssl-expiration-check.sh
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}